package room

//每个房间的设置数据
type RoomSettings struct {
	LenOfName          uint8
	RoomName           []byte
	Unk00              uint8
	Unk01              uint8
	Unk02              uint32
	Unk03              uint32
	LenOfPassWd        uint8
	PassWd             []byte
	Unk10              uint16
	ForceCamera        uint8
	GameModeID         uint8
	MapID              uint8
	Unk13              uint8
	MaxPlayers         uint8
	WinLimit           uint8
	KillLimit          uint16
	Unk17              uint8
	Unk18              uint8
	WeaponRestrictions uint8
	Status             uint8
	Unk21              uint8
	MapCycleType       uint8
	Unk23              uint8
	Unk24              uint8
	Unk25              uint8
	LenOfMultiMaps     uint8
	MultiMaps          []byte
	TeamBalanceType    uint8
	Unk29              uint8
	Unk30              uint8
	Unk31              uint8
	Unk32              uint8
	Unk33              uint8
	AreBotsEnabled     uint8
	BotDifficulty      uint8
	NumCtBots          uint8
	NumTrBots          uint8
	Unk35              uint8
	Unk36              uint8
	Unk37              uint8
	Unk38              uint8
	Unk39              uint8
	StartMoney         uint16
	ChangeTeams        uint8
	Unk43              uint8
	HltvEnabled        uint8
	Unk45              uint8
	RespawnTime        uint8
	NextMapEnabled     uint8
	Difficulty         uint8
	IsIngame           uint8
}
